membersrvc_auth:
   image: hyperledger/fabric-membersrvc
   environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
   command: membersrvc

vp0:
  extends:
    file: compose-consensus-4-defaults.yml
    service: vp
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_PRIVACY=true
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT


vp1:
  extends:
    service: vp0
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_PRIVACY=true
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy

vp2:
  extends:
    service: vp0
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_PRIVACY=true
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ


vp3:
  extends:
    service: vp0
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_PRIVACY=true
    - CORE_PEER_ID=vp3
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
