membersrvc_auth:
   image: hyperledger/fabric-membersrvc
   environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
   command: membersrvc

cli:
  image: hyperledger/fabric-peer
  command: ./infiniteloop.sh
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_SECURITY_ENABLED=false

vp0_auth:
  extends:
    file: compose-consensus-4-defaults.yml
    service: vp_auth
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=false
    - CORE_PEER_ID=vp0_auth
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT


vp1_auth:
  extends:
    service: vp0_auth
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=false
    - CORE_PEER_ID=vp1_auth
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0_auth:7051
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy


vp2_auth:
  extends:
    service: vp0_auth
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=false
    - CORE_PEER_ID=vp2_auth
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0_auth:7051
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ


vp3_auth:
  extends:
    service: vp0_auth
  environment:
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_SECURITY_ENABLED=false
    - CORE_PEER_ID=vp3_auth
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0_auth:7051
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
